[package]
name = "zack"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "4", features = ["cargo"]}
egui = "0.20"
eframe = "0.20"
ringbuffer = "0.11.1"
